baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir="docs"
disqusShortname = "dev-learning"
[params]
  afterDomain='tutorials'
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[taxonomies]
  category="categories"
  tag="tags"
  authors="authors"
  course='courses'
  course-tag='course-tags'
  course-parent='course-parents'
